version: '3'

services:
  nginx:
    image: ghcr.io/richardds/php
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - ALPINE_VERSION=3.17
        - COMPOSER_VERSION=2.5.1
    restart: unless-stopped
