name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composer:
          -
            tag: 2.2
            version: 2.2.18
          -
            tag: 2.5
            version: 2.5.1
        php_versions:
          -
            alpine: 3.15
            php: 7.4
            dockerfile: Dockerfile74
          -
            alpine: 3.17
            php: 8.1
            dockerfile: Dockerfile81
          -
            alpine: edge
            php: 8.2
            dockerfile: Dockerfile82
    steps:
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.php_versions.dockerfile }}
          build-args: |
            ALPINE_VERSION=${{ matrix.php_versions.alpine }}
            COMPOSER_VERSION=${{ matrix.composer.version }}
          push: true
          tags: |
            richardboldis/php:latest
            richardboldis/php:${{ matrix.php_versions.php }}
            richardboldis/php:${{ matrix.php_versions.php }}-${{ github.ref_name }}
            richardboldis/php:${{ matrix.php_versions.php }}-${{ github.ref_name }}-composer${{ matrix.composer.tag }}
            ghcr.io/richardds/php:latest
            ghcr.io/richardds/php:${{ matrix.php_versions.php }}
            ghcr.io/richardds/php:${{ matrix.php_versions.php }}-${{ github.ref_name }}
            ghcr.io/richardds/php:${{ matrix.php_versions.php }}-${{ github.ref_name }}-composer${{ matrix.composer.tag }}
