name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            ALPINE_VERSION=3.17
            COMPOSER_VERSION=2.3
          push: true
          tags: |
            richardboldis/docker-php:latest
            richardboldis/docker-php:${{ github.ref_name }}
            ghcr.io/richardds/docker-php:latest
            ghcr.io/richardds/docker-php:${{ github.ref_name }}
